### ISSUE TITLE
After tabulation on "<button", data-whatintent switch to "keyboard"

### ISSUE THREAD

**Issue by Diicepoo** [ten1seven/what-input#103]
After tabulation on "<button", data-whatintent switch to "keyboard".

You can see at: https://ten1seven.github.io/what-input/

1) Click on input
2) MAJ + TAB for going to button
3) TAB
= Now, input is bordered

It's not logic, because if you do:
1) Click on input
2) MAJ for going on next input
= input is still no bordered

**Comment by Diicepoo** [comment]
I closed the issue because although I have abnormal behavior on my application, the diagnosis of this issue is not good.

**Comment by Diicepoo** [comment]
I had abnormal behavior in my application (Angular) because I did not have a `<form`> tag

**Comment by ten1seven** [comment]
Okay, thanks for the follow up on that @Diicepoo !
