### ISSUE TITLE
Follow convention to put sourcemap in same folder as minified file

### ISSUE THREAD

**Issue by vwkd** [ten1seven/what-input#104]
I am using what-input as one of many modules in my build workflow, which puts them all into one folder. I can not put the sourcemap for what-input in a separate `maps` folder, while all other modules follow the convention to keep the sourcemaps in the same folder as the `.min.js`. It would be great if this could be fixed.

**Comment by ten1seven** [comment]
Hey @zjopy I just made this update here https://github.com/ten1seven/what-input/commit/6ae250e150e050c08fcc6448c8ee5dcb85f2167a. Check out v5.2.7
