### ISSUE TITLE
Degrade gracefully in unsupported browsers

### ISSUE THREAD

**Issue by slavanga** [ten1seven/what-input#13]
I would like to see a simple “cut the mustard” style check to prevent errors in old browsers. There is a polyfill for IE 8 but I think the utility should degrade gracefully even without the polyfill.

A simple check like this would be enough to prevent errors:

``` js
if(!'addEventListener' in window && !!Array.prototype.indexOf) return;
```

**Comment by ten1seven** [comment]
Excellent suggestion! I might look at doing a more specific "mustard cutting" specific to the features I'm using and see about testing for the polyfills as well so there doesn't need to be two versions (polyfill and non-polyfill supported).

**Comment by ten1seven** [comment]
Thanks again for the suggestion! Let me know if you have any issues with that working in the wild.

**Comment by slavanga** [comment]
Awesome! Thank you for the quick implementation.
Looks good so far...
