### ISSUE TITLE
IE Not Working

### ISSUE THREAD

**Issue by realalexhomer** [ten1seven/what-input#14]
Hey,
I'm curious if anyone has gotten this to work on IE? I've tested on IE 9 and IE 10 to no avail. Its not a polyfill error as there is no error being thrown.

The script is initializing and the body is getting a mouse data attribute, but keyboard events are not causing this attribute to change. 

If someone else can verify its not just me I'd be happy to fix it and submit a pr.

**Comment by ten1seven** [comment]
Hey @realalexhomer, I can confirm that this works in IE8+ (just re-checked in my virtual machines). If you use the [demo page](http://ten1seven.github.io/what-input) is it still not working?

**Comment by realalexhomer** [comment]
Thanks, sorry to bother you, it does appear to be working. I must have an event listener buried somewhere that is not propagating changes for ie for some reason.

**Comment by ten1seven** [comment]
Happy to help if I can!

The keyboard events are bound on the `body` and `document`. If you're using `event.stopPropagation()` on keyboard events on elements in the page or are binding to the `<body>` and using `event.preventDefault()` that could be interfering with what input.
