### ISSUE TITLE
Compatibility with Chrome Emulation Mode

### ISSUE THREAD

**Issue by solomonhawk** [ten1seven/what-input#15]
When testing with Chrome Emulator mode set to iPhone(or other touch device), `what-input` fails to bind the `touchstart` event since `'ontouchstart' in document.documentElement` is false. Instead we should be checking for `'ontouchstart' in window` which is true in Chrome when Device Emulation is active [via Modernizr](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/touchevents.js).

http://stackoverflow.com/questions/28544445/how-to-detect-device-mode-emulation
http://www.stucox.com/blog/you-cant-detect-a-touchscreen/

**Comment by solomonhawk** [comment]
@ten1seven do you know whether this change can/will break other functionality of `what-input`?

**Comment by ten1seven** [comment]
It shouldn't hurt anything at all. Are you proposing I replace this:

``` javascript
if ('ontouchstart' in document.documentElement) {
```

With the whole `if` from Modernizr?

``` javascript
if (('ontouchstart' in window) || window.DocumentTouch && document instanceof DocumentTouch) {
```

Or just this?

``` javascript
if ('ontouchstart' in window) {
```
