### ISSUE TITLE
Persist previous state when typing

### ISSUE THREAD

**Issue by craigmdennis** [ten1seven/what-input#2]
Not sure on the best approach but it would be nice to be able to still have 'mouse' set when typing in an input if the `:focus` was triggered by a click (or tap etc.).
- Persist previous input method
- Option to set keyboard input to only trigger on tab

**Comment by craigmdennis** [comment]
I've added the following:

``` js
body.addEventListener('keydown', function(event){
  if (event.keyCode == 9) { // Tab
    regularInput(event)
  }
});
```

**Comment by craigmdennis** [comment]
Ok, I see that I can probably do this with the API (coffeeScript)

``` coffee
# Set a custom 'typing' input
$('input').on 'input', ->
  whatInput.set('typing')
```

**Comment by craigmdennis** [comment]
Ok, that's still not as effective as only tracking the Tab `keyCode`. Suggestions?

**Comment by ten1seven** [comment]
Hi Craig,

This is a good feature that I missed! You caught me while I've been traveling since last Wednesday so I haven't had time to sit down and look. I'll be back at my desk tomorrow and let you know what I figure out.

**Comment by ten1seven** [comment]
Hey Craig,

I just created this [pull request](https://github.com/ten1seven/what-input/pull/3) that ignores typing in form fields. I'd appreciate if you'd take a look and see what you think. 

I was thinking of allowing developers to set a data attribute flag on the body to _ignore_ this behavior. Something like `data-whatinput-allowformtyping`, but the default behavior would be to ignore form field typing. Thoughts?

**Comment by craigmdennis** [comment]
Looks good! I agree that it should ignore inputs by default. Not sure about `data-whatinput-allowformtyping`, seems a little verbose.
