### ISSUE TITLE
Ignore certain key presses

### ISSUE THREAD

**Issue by philwolstenholme** [ten1seven/what-input#28]
I'm using what-input to switch between photo captions appearing when hovering over a photo, and appearing underneath the photo, depending on whether the user is a mouse user or not. Switching input type causes a page reflow as the captions take up more vertical space.

If I go to click on a photo with my Ctrl key pressed (to open the photo link in a new tab) then the input type is changed and the page reflows, making content jump around just as a user is trying to click on it.

Would it be possible to ignore certain key codes? I would want tab, space, enter etc to trigger keyboard input mode, but perhaps not keys that are often used in conjunction with mouse input.

**Comment by ten1seven** [comment]
Good catch! I don't see any down side to ignoring the modifier keys. Looks like the list is `SHIFT`, `ALT` and `CTRL`. I'll probably be able to get something out by tomorrow.

**Comment by philwolstenholme** [comment]
Glad you like the idea!

> I'll probably be able to get something out by tomorrow.

Wow! There's no rush from my point of view at all, as this is just a _nice-to-have_. The time you've put into this project is super appreciated.

**Comment by ten1seven** [comment]
Just published [v1.2.5](https://github.com/ten1seven/what-input/releases/tag/v1.2.5) to ignore those keys.  I'd love to get your feedback after trying it out in your app. Thanks for the suggestion!

**Comment by philwolstenholme** [comment]
Sorry for the delay in getting back to you about this @ten1seven . I've added some Apple specific keys (the command keys used for opening links in new tabs on a OS X machine) to the ignore list in this pull request: #29

**Comment by philwolstenholme** [comment]
For anyone else proposing keycodes to ignore, http://keycode.info is a useful resource.

**Comment by ten1seven** [comment]
Thanks for submitting a PR! Always nice when someone wants to pitch in. Please note that I'm at version 2.0.1 due to a breaking change in the UMD wrapper. If you're using a package manager it probably won't pull in the update unless you bump the version.
