### ISSUE TITLE
Publish to NPM :)

### ISSUE THREAD

**Issue by greypants** [ten1seven/what-input#5]
**Hurry while the name is available!**

How-to:
https://docs.npmjs.com/getting-started/publishing-npm-packages

Package.json config info: 
https://docs.npmjs.com/files/package.json

don't forget to add 

```
npm install what-input
```

and 

``` js
var whatInput = require('what-input')
```

To the README.

**Comment by ten1seven** [comment]
Fixed by @jgarber623

**Comment by greypants** [comment]
:+1: :+1: :+1: :+1: :+1:  Already installed and using!

**Comment by simevidas** [comment]
@ten1seven Also update the Installing section in the README. Otherwise, some people might think that only bower is supported.
