### ISSUE TITLE
RequireJS fails ~ missing amd support

### ISSUE THREAD

**Issue by artursopelnik** [ten1seven/what-input#51]
Currently we use "what-input" in version _"2.1.1"_. Because it is the last working version for our development process with requirejs.

Version 3 and up loaded uncorrectly. Unfortunately there is no error message ... 

Could you try to import dist files via requirejs …

**Comment by ten1seven** [comment]
Hi @artursopelnik, I'll take a look into it.

**Comment by ten1seven** [comment]
Hey @artursopelnik, I gotta admit, this is tripping me up. In the current version I'm supporting UMD via Webpack. Do you have any suggestions for a UMD/AMD compatible wrapper?

**Comment by artursopelnik** [comment]
Sorry it was my mistake. You have to be include it with the same module name.

**Before:**
`'what-input': '../../node_modules/what-input/dist/what-input',`

**After:**
`'whatInput': '../../node_modules/what-input/dist/what-input',`

It is unusual that filename and module name are different. Maybe it makes sense to adjust.

**Comment by ten1seven** [comment]
Ah, yes. Good find! I don't want to make a change that would break this for others so I'll add how to do this to the README and keep it in mind for the next major update. Thanks!
