### ISSUE TITLE
Scrolling page with mouse in window changes intent

### ISSUE THREAD

**Issue by jasonhibbs** [ten1seven/what-input#52]
`[data-whatintent]` is changed to `mouse` if the pointer is in a window when the page scrolls. I believe this is because `mousemove` is fired.

**Comment by ten1seven** [comment]
Nice catch @jasonhibbs, thanks!

**Comment by ten1seven** [comment]
@jasonhibbs just published an fix for this as version 4.1.0. Please take a look and let me know what you think.

**Comment by jasonhibbs** [comment]
Solves the issue perfectly where checked in Chrome, thanks!

**Comment by ten1seven** [comment]
Sweet!
