### ISSUE TITLE
Ignore some keys?

### ISSUE THREAD

**Issue by FezVrasta** [ten1seven/what-input#56]
For example, I have a component that accepts CMD + Click.

I would like the `data-whatinput` to stay to `mouse` since the user isn't actually going to use the keyboard to navigate the app in any way.

Having the ability to define a list of ignored keys would be handy.

**Comment by ten1seven** [comment]
Hey @FezVrasta, there's already a [list of ignored keys](https://github.com/ten1seven/what-input/blob/master/src/what-input.js#L24) that includes CMD, however I'm seeing a bug where the key is ignored correctly on `keydown` but missed on `keyup`. I'll look into that!

**Comment by ten1seven** [comment]
@FezVrasta just pushed up v4.1.2 that should fix the mouse modifier keys. Let me know if that does the trick.

**Comment by ten1seven** [comment]
I've been working on [v5.0.0](https://github.com/ten1seven/what-input/tree/version-five) and added an API option to overwrite the default ignored keys:

```javascript
whatInput.ignoreKeys([1, 2, 3])
```

**Comment by FezVrasta** [comment]
It fixed it, thank you!
