### ISSUE TITLE
Unnecessary console.log statement

### ISSUE THREAD

**Issue by treetrum** [ten1seven/what-input#57]
Is there a need for the `console.log(value)` statement on line 129 of what-input.js ?

It's not a real issue, just like to see my console clean unless there's an issue present.

**Comment by ten1seven** [comment]
Yikes! Was just fixing an issue and debugging _last night_ and left that in there on accident. You are very quick! Thanks!

**Comment by treetrum** [comment]
Hahaha! Just good timing I guess. I happened to start a new project today!
