### ISSUE TITLE
Uncaught ReferenceError: module is not defined

### ISSUE THREAD

**Issue by NucleaPeon** [ten1seven/what-input#60]
I'm not using bower or npm to install what-input.js, I'm simply using the src file.
My import tag:

    <script src="js/vendor/what-input.js"></script>

It exists at that location because it was working with a previous version at the same location.

I'm getting an error:

    Uncaught ReferenceError: module is not defined
        at what-input.js:1

Am I doing something wrong in my usage/installation, or is this an actual bug? Using latest master branch as of May 23, 2017 (4pm).

Using Chrome Version 58.0.3029.110 (64-bit) on Mac OS X 10.12.5

**Comment by NucleaPeon** [comment]
As an aside, I would also like to suggest adding in a version variable into the source file, or a version comment.

**Comment by ten1seven** [comment]
Hi @NucleaPeon. Yes the file locations got moved around when I updated to use Webpack. Your new file location is `dist/what-input.js` or `dist/what-input.min.js`. I'll make a note to add a version variable. Thanks!

**Comment by NucleaPeon** [comment]
Works perfectly! Thank you
