### ISSUE TITLE
Consider using “passive” event listener for mouse wheel event

### ISSUE THREAD

**Issue by tedw** [ten1seven/what-input#63]
FYI, Chrome displays the following message in the console in “verbose” mode:
>preload.js:642 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.

Is there any downside to converting to “passive” event listeners?

More info:
https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md

Thanks for everyone’s hard work on this! I use it on all my projects.

**Comment by ten1seven** [comment]
Thanks @tedw, I'll get this rolled in!

**Comment by ten1seven** [comment]
@tedw just added this, verified that it adds the listener passively and removes the alert from the console and published a new package.

**Comment by tedw** [comment]
@ten1seven Awesome, thanks!
