### ISSUE TITLE
Can't find variable: mobiGetClick

### ISSUE THREAD

**Issue by kendagriff** [ten1seven/what-input#78]
Does anyone have any idea where this error might be originating: `Can't find variable: mobiGetClick`?

It appeared on iPads in iOS 11.3 immediately after I added the what-input library. I can't reproduce the error, but it's appearing in our production logs. And `mobiGetClick` is virtually unfindable on the internet. Any ideas?

P.S. Thanks for a great library!

**Comment by ten1seven** [comment]
Hi @kendagriff `mobiGetClick` is not a variable related to what input. Is that error popping up on page load or when you start interacting with the page? I would suspect another third-party script.

**Comment by kendagriff** [comment]
That's perfectly possible, yes. We're going to deactivate what-input and see if it disappears or if it was merely coincidence.
