### ISSUE TITLE
Chrome "emulate touch" returns as "mouse"?

### ISSUE THREAD

**Issue by averyvery** [ten1seven/what-input#8]
I know this isn't the primary use case, but I was surprised to see that what-input doesn't see chrome's "emulate touch" clicks as touches. This is probably because emulate touch is a hack and what-input is doing something clever, but if you have any ideas and it's a quick fix, that would be cool.

**Comment by ten1seven** [comment]
I found [this article](https://developer.chrome.com/devtools/docs/device-mode#touch-emulation) that worked for me. There's a flag in `chrome://flags` that you need to enable.

![screen shot 2015-05-22 at 08 55 54](https://cloud.githubusercontent.com/assets/137020/7773252/772e43fc-0060-11e5-8868-752208e74301.png)

**Comment by averyvery** [comment]
Awesome, that worked! :+1:
