### ISSUE TITLE
clarification of whatintent

### ISSUE THREAD

**Issue by cminkwitz** [ten1seven/what-input#87]
First of all let me say thank you for your work. I really appreciate it.

Could you please clarify the the meaning of the whatintent attribute. In the demo the whatintent attribute switches to 'mouse' when ever one moves the mouse, which is reasonable. But to get it into keyboard state, one has to tab to the links in the top area. In case one just tabs inside the form, it stays in mouse state. I do not fully understand, what the whatintent attribute should tell me in this case.

Thanks

**Comment by chesio** [comment]
Hi,

This has been asked [before](https://github.com/ten1seven/what-input/issues/50) and is [explained in README](https://github.com/ten1seven/what-input#interacting-with-forms).
