### ISSUE TITLE
Mouse wheel doesn't trigger any changes

### ISSUE THREAD

**Issue by matteobad** [ten1seven/what-input#95]
# Mouse wheel doesn't trigger any changes.

I would expect the mouse wheel to trigger a change. But when scrolling the wheel no changes occurs. I'm not entirely sure, but I think that a wheel event should be treated similarly to a mouse/pointer move event. Let me know what you think about this. Thanks in advance and keep up the great work.

## Step to reproduce:

1. Open the [demo](https://ten1seven.github.io/what-input/)
2. Start navigating with keyboard
3. Use the mouse wheel without moving the pointer
4. No changes in what-input or what-intent

## Expected behavior:

- what-intent should become _mouse_?

**Comment by ten1seven** [comment]
Hi @matteobad,

There actually is mousewheel support built in, but it appears that it's not functioning as it should so I'm going to take a look at it.

https://github.com/ten1seven/what-input/blob/master/src/scripts/what-input.js#L318-L334

**Comment by ten1seven** [comment]
I made an update in the latest release ([v5.2.3](DOMMouseScroll)) that addresses mousewheel not always being detected. Please note that `wheel`, `mousewheel`, and `DOMMouseScroll` all report as `mouse`.

If you have any issues, please re-open this ticket.

**Comment by matteobad** [comment]
Thank you for your rapid response 👍
