### ISSUE TITLE
Demo site: some liks are broken

### ISSUE THREAD

**Issue by trymoto** [ten1seven/what-input#98]
Hello.
On your demo site (https://ten1seven.github.io/what-input/) there are 2 links in the bottom that lead to `http://viget.com/` and `https://github.com/ten1seven/what-input` that probably get `preventDefault()` and don't work as expected.

**Comment by ten1seven** [comment]
😂 🤦‍♂  thanks for catching this @trymoto !

**Comment by ten1seven** [comment]
This is fixed here https://github.com/ten1seven/what-input/commit/e045a2a1e4cc5b31e0291be19656f0fa0ad85c01!
